export class WalletSdkError extends Error {
  code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = "WalletSdkError";
    this.code = code;
  }
}

export const WalletErrorCodes = {
  PROVIDER_NOT_FOUND: "PROVIDER_NOT_FOUND",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  DECRYPT_FAILED: "DECRYPT_FAILED",
  UNSUPPORTED_METHOD: "UNSUPPORTED_METHOD",
  USER_REJECTED: "USER_REJECTED",
  INVALID_PARAMS: "INVALID_PARAMS",
  CHAIN_SWITCH_REJECTED: "CHAIN_SWITCH_REJECTED",
  CHAIN_NOT_ADDED: "CHAIN_NOT_ADDED",
  TRANSACTION_FAILED: "TRANSACTION_FAILED",
  RPC_UNAVAILABLE: "RPC_UNAVAILABLE",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  NONCE_CONFLICT: "NONCE_CONFLICT",
  GAS_ESTIMATION_FAILED: "GAS_ESTIMATION_FAILED",
  MNEMONIC_INVALID: "MNEMONIC_INVALID",
  STORAGE_CORRUPTED: "STORAGE_CORRUPTED"
} as const;
